### PR TITLE
Workaround for GitHub shivammathur/php-setup auth

### PR DESCRIPTION
**Pull request by naderman**

### CODE REVIEW

**Review by glaubinix — APPROVED** [review]

**Comment by loevgaard** [comment]
This is perfect and much better than I could have explained it :D

**Comment by naderman** [comment]
Looks like there is now a different documented way to define additional composer repos, so guess we could update this again: https://github.com/shivammathur/setup-php#manual-composer-authentication?

**Comment by naderman** [comment]
Actually missed there's even a specific setting for Private Packagist: https://github.com/shivammathur/setup-php#private-packagist-authentication

**Comment by loevgaard** [comment]
Hehe, it was added two days after this PR. Probably other people experienced the same problems :)

**Pull request merged**
