### PR TITLE
Adding a package via custom JSON

### PR DESCRIPTION
**Pull request by wissem**
a guide to explain format for adding a package via custom JSON.
Let me know if there are other details that needs to be mentioned here.

### CODE REVIEW

**Comment by naderman** [comment]
Maybe we can make this a document about Adding packages in general, even if for now we just have one section for custom JSON ones? I think I prefer a bit more content on one page. Our help link can then just go to the relevant section in the document.

**Comment by glaubinix** [comment]
We can probably merge this with https://github.com/packagist/private-packagist-docs/pull/5/files

**Comment by wissem** [comment]
Ok, I can close this one and just update the "Add a custom package" section in https://github.com/packagist/private-packagist-docs/pull/5/files  with some examples and link to it then?

**Comment by naderman** [comment]
Sounds good!

**Pull request closed without merging**
